CREATE database tmp CHARACTER SET utf8 COLLATE utf8_bin;

USE tmp;

CREATE TABLE roles(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    label VARCHAR(255)
);
