CREATE DATABASE IF NOT EXISTS tagBeSill;

USE tagBeSill;

CREATE TABLE IF NOT EXISTS Status(
	id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    label VARCHAR(255) NOT NULL,
    description BLOB NOT NULL
) engine InnoDB;

CREATE TABLE IF NOT EXISTS Project(
	id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description BLOB NOT NULL,
    image VARCHAR(255) DEFAULT NULL,
    publishingDate DATETIME DEFAULT NULL,
    creationDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    statusId INTEGER UNSIGNED NOT NULL,
    FOREIGN KEY (statusId) REFERENCES status(id)
) engine InnoDB;

CREATE TABLE IF NOT EXISTS Category(
	id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    label VARCHAR(255) NOT NULL,
    description BLOB NOT NULL
) ENGINE InnoDB;

CREATE TABLE IF NOT EXISTS ProjectCategory(
	projectId INTEGER UNSIGNED,
    categoryId INTEGER UNSIGNED,
    PRIMARY KEY (projectId, categoryId),
    FOREIGN KEY (projectId) REFERENCES Project(id),
    FOREIGN KEY (categoryId) REFERENCES Category(id)
) ENGINE InnoDB;
