
CREATE TABLE Role(
	id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    label VARCHAR(255) NOT NULL,
    description BLOB NOT NULL
) ENGINE InnoDB;

CREATE TABLE User(
	id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nickname VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
	roleId INTEGER UNSIGNED,
    FOREIGN KEY (roleId) REFERENCES Role(id)
) ENGINE InnoDB;

CREATE TABLE ProjectUser(
	projectId INTEGER UNSIGNED,
	userId INTEGER UNSIGNED,
	PRIMARY KEY (projectId, userId),
    FOREIGN KEY (projectId) REFERENCES Project(id),
    FOREIGN KEY (userId) REFERENCES User(id)
) ENGINE InnoDB;
